version: '3.8'
services:
  db:
    container_name: mysql8
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seeddms_db
      MYSQL_USER: seeduser
      MYSQL_PASSWORD: seedpass
    volumes:
        - './baza:/var/lib/mysql'  
    ports:
      - 3306:3306

  mailcatcher:
    image: yappabe/mailcatcher
    container_name: mailowy
    ports:
        - 1025:1025
        - 1080:1080

  ldap:
    image: rroemhild/test-openldap
    container_name: ldap_server
    restart: always
    ports:
        - 389:389
        - 636:636

  # Po uruchomieniu należy uruchomić skrypt /startup.sh
  seed:
    build: ./seed
    container_name: SEED
    restart: always
    image: barricadepl/seed_dms_full:1.0
    volumes:
      - './seed/conf:/var/www/seeddms60x/conf'  
      - './seed/pliki:/home/data'  
      - './seed/lang:/var/www/seeddms60x/www/languages/pl_PL'
    ports:
      - 8080:80
    depends_on:
      - db

